#!/bin/bash

# Sum of multiples of 2 and 5 less than 1000 using bash.
sum=0
for i in {0..999}
do
    if [ $(($i%3)) = 0 ]
    then
        sum=$(($sum+$i))
        continue
    fi
    [ $(($i%5)) = 0 ] && sum=$(($sum+$i))
done
echo $sum
